---
title: Series of Hackerrank Competitions
author: ~
date: '2019-09-24'
subtitle: 'A few simple Hackerrank competitons consisting of time series and cross sectional problems'
summary: 'I show my solutions to a few Hackerrank competitions/problems I had completed and discuss the models and solutions.'

categories: [Hackerrank]
projects: [Machine Learning]
tags: [machine learning, hackerrank, time series, xgboost]

output:
  html_document:
    code_folding: hide
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<pre class="r"><code>library(knitr)
library(kableExtra)
library(ggplot2)
library(tidyquant)
library(dplyr)</code></pre>
<div id="problem-1-battery-life-prediction-problem" class="section level4">
<h4>Problem 1: Battery Life Prediction Problem</h4>
<p>The first problem was to predict how long a laptop would last given the number of hours it was charged. The problem is <a href="https://www.hackerrank.com/challenges/battery/problem">here</a></p>
<p>We can read in the data directly from the hackerrank website using the following:</p>
<pre class="r"><code>BatteryData &lt;- read.table(file = url(&quot;https://s3.amazonaws.com/hr-testcases/399/assets/trainingdata.txt&quot;), strip.white = TRUE, sep = &#39;,&#39;, header = FALSE, skip = 0)</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-3">Table 1: </span>Battery Life Data
</caption>
<thead>
<tr>
<th style="text-align:right;">
V1
</th>
<th style="text-align:right;">
V2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2.81
</td>
<td style="text-align:right;">
5.62
</td>
</tr>
<tr>
<td style="text-align:right;">
7.14
</td>
<td style="text-align:right;">
8.00
</td>
</tr>
<tr>
<td style="text-align:right;">
2.72
</td>
<td style="text-align:right;">
5.44
</td>
</tr>
<tr>
<td style="text-align:right;">
3.87
</td>
<td style="text-align:right;">
7.74
</td>
</tr>
<tr>
<td style="text-align:right;">
1.90
</td>
<td style="text-align:right;">
3.80
</td>
</tr>
<tr>
<td style="text-align:right;">
7.82
</td>
<td style="text-align:right;">
8.00
</td>
</tr>
</tbody>
</table>
<p>At first thought I applied a simple time series model to the data and obtained poor predictions. I then took a closer look at the actual data by plotting it and it told a different story.</p>
<pre class="r"><code>BatteryData %&gt;%
  ggplot(aes(x = V1, y = V2)) + 
  geom_point() +
  stat_smooth(method = &quot;lm&quot;, col = &quot;red&quot;) +
  geom_vline(xintercept = 4) +
  theme_tq()</code></pre>
<p><img src="/post/hackerrank-competitions/hackerrank-compeitions_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>I drew a horizontal line at 4 hours of battery life and plotted a linear regression line - quite clearly it performs badely and I needed to find a different model or better yet set a threshold and predict all observations whose battery had been charging for 4 or more hours to be fully charged.</p>
<p>The model:</p>
<pre class="r"><code>LinearPredictionModel &lt;- function(TestData){
  TrainData &lt;- read.table(file = url(&quot;https://s3.amazonaws.com/hr-testcases/399/assets/trainingdata.txt&quot;), strip.white = TRUE, sep = &#39;,&#39;, header = FALSE, skip = 0)
  
  TrainData$LessThanFour &lt;- ifelse(TrainData[, 2] &lt; 4, 1, 0)
  
  LMData &lt;- TrainData %&gt;%
    filter(LessThanFour == 1)
  
  LinearModel &lt;- lm(V1 ~ V2, data = LMData) 
  
  TestData &lt;- data.frame(V2 = TestData)
  
  STDOUT &lt;- ifelse(TestData &lt; 4, predict(LinearModel, newdata = TestData), 8)
  
  return(cat(STDOUT))
}</code></pre>
<p>The model basically tells us that if the data is less than 4, then fit a simple linear regression model if it is greater or equal to 4 then just apply an 8 prediction.</p>
<p>We can input some new data as follows:</p>
<pre class="r"><code>TestData &lt;- c(5, 8, 1, 0.2, 3.5, 5.6, 4.32)
LinearPredictionModel(TestData)</code></pre>
<pre><code>## 8 8 0.5 0.1 1.75 8 8</code></pre>
</div>
<div id="problem-2-house-price-prediction-problem-using-xgboost" class="section level4">
<h4>Problem 2: House Price Prediction Problem using XGBoost</h4>
<p>In this problem I want to train an XGBoost (Extreme Gradient Boosting) model to predict what a house is going to be based on some characteristics. There is a house price prediction problem on Hackerrank <a href="https://www.hackerrank.com/challenges/predicting-house-prices/problem">here</a> but I used the pre-installed base R house prices data.</p>
<pre class="r"><code>library(AER)
library(car)
library(dplyr)
library(xgboost)
library(tidyquant)
library(Metrics)</code></pre>
<p>Load in the data and set factors to numeric for easier pre-processing.</p>
<pre class="r"><code>data(&quot;HousePrices&quot;)

data &lt;- HousePrices %&gt;%
  mutate_if(is.factor, as.numeric)</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-9">Table 2: </span>House Price Data
</caption>
<thead>
<tr>
<th style="text-align:right;">
price
</th>
<th style="text-align:right;">
lotsize
</th>
<th style="text-align:right;">
bedrooms
</th>
<th style="text-align:right;">
bathrooms
</th>
<th style="text-align:right;">
stories
</th>
<th style="text-align:right;">
driveway
</th>
<th style="text-align:right;">
recreation
</th>
<th style="text-align:right;">
fullbase
</th>
<th style="text-align:right;">
gasheat
</th>
<th style="text-align:right;">
aircon
</th>
<th style="text-align:right;">
garage
</th>
<th style="text-align:right;">
prefer
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
42000
</td>
<td style="text-align:right;">
5850
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
38500
</td>
<td style="text-align:right;">
4000
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
49500
</td>
<td style="text-align:right;">
3060
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
60500
</td>
<td style="text-align:right;">
6650
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
61000
</td>
<td style="text-align:right;">
6360
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
66000
</td>
<td style="text-align:right;">
4160
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<p>Split the data between 80% train and 20% testing.</p>
<pre class="r"><code>####################################################################################
# For this example split between train and test
smp_size &lt;- floor(nrow(data) * 0.80)

train_ind &lt;- sample(seq_len(nrow(data)), size = smp_size)

train &lt;- data[train_ind, ]
test &lt;- data[-train_ind, ]

paste(&quot;Train Dimensions&quot;); dim(train)</code></pre>
<pre><code>## [1] &quot;Train Dimensions&quot;</code></pre>
<pre><code>## [1] 436  12</code></pre>
<pre class="r"><code>paste(&quot;Test Dimensions&quot;); dim(test)</code></pre>
<pre><code>## [1] &quot;Test Dimensions&quot;</code></pre>
<pre><code>## [1] 110  12</code></pre>
<p>I create the function to take the training and testing data, train a model and output the predictions. I omit the cross-validation and hype-parameter tuning here but I will write a post detailing how I use a grid search to find the optimal parameters of an XGBoost model soon, (it takes some explaining of the functions I create).</p>
<pre class="r"><code>####################################################################################
predictHouseSales &lt;- function(train_data, test_data){
  x_train &lt;- subset(train_data, select = c(-price))
  y_train &lt;- subset(train_data, select = c(price)) %&gt;% pull(price)
  
  x_test &lt;- subset(test_data, select = c(-price))
  y_test &lt;- subset(test_data, select = c(price)) %&gt;% pull(price)
  
  dtrain &lt;- xgb.DMatrix(data = as.matrix(x_train), label = y_train, missing = &quot;NaN&quot;)
  dtest &lt;- xgb.DMatrix(data = as.matrix(x_test), missing = &quot;NaN&quot;)
  
  params &lt;- list(
    &quot;eta&quot; = 0.1, 
    &quot;max_depth&quot; = 5, 
    &quot;objective&quot; = &quot;reg:linear&quot;,
    &quot;eval_metric&quot;= &quot;rmse&quot;
    )
  
  xgb.model &lt;- xgb.train(params, dtrain, nrounds = 100)
  
  return(predict(xgb.model, newdata = dtest))
  
}

myPredictions &lt;- predictHouseSales(train, test)</code></pre>
<p>We can inspect some of the predictions and compare them to the actual preditions below:</p>
<pre class="r"><code>####################################################################################
myPredictions %&gt;%
  data.frame() %&gt;%
  setNames(c(&quot;myPreds&quot;)) %&gt;%
  mutate(myPreds = round(myPreds, 0)) %&gt;%
  bind_cols(test) %&gt;%
  select(myPreds, price) %&gt;%
  sample_n(5) %&gt;%
  kable(caption = &quot;Compare predictions to the observed&quot;) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;), font_size = 12)</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-12">Table 3: </span>Compare predictions to the observed
</caption>
<thead>
<tr>
<th style="text-align:right;">
myPreds
</th>
<th style="text-align:right;">
price
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
49942
</td>
<td style="text-align:right;">
39000
</td>
</tr>
<tr>
<td style="text-align:right;">
117177
</td>
<td style="text-align:right;">
115442
</td>
</tr>
<tr>
<td style="text-align:right;">
65904
</td>
<td style="text-align:right;">
34000
</td>
</tr>
<tr>
<td style="text-align:right;">
65651
</td>
<td style="text-align:right;">
42000
</td>
</tr>
<tr>
<td style="text-align:right;">
48866
</td>
<td style="text-align:right;">
65000
</td>
</tr>
</tbody>
</table>
<p>Compute the Root Mean Square Error:</p>
<pre class="r"><code>####################################################################################
myPredictions %&gt;%
  data.frame() %&gt;%
  setNames(c(&quot;myPreds&quot;)) %&gt;%
  mutate(myPreds = round(myPreds, 0)) %&gt;%
  bind_cols(test) %&gt;%
  select(myPreds, price) %&gt;%
  summarise(rmse(myPreds, price)) %&gt;%
  kable(caption = &quot;Compute the RMSE&quot;) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;), font_size = 12)</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-13">Table 4: </span>Compute the RMSE
</caption>
<thead>
<tr>
<th style="text-align:right;">
rmse(myPreds, price)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
16266.12
</td>
</tr>
</tbody>
</table>
<p>We can also plot the predictions against the observed using <code>ggplot2</code>:</p>
<pre class="r"><code>####################################################################################
myPredictions %&gt;%
  data.frame() %&gt;%
  setNames(c(&quot;myPreds&quot;)) %&gt;%
  mutate(myPreds = round(myPreds, 0)) %&gt;%
  bind_cols(test) %&gt;%
  select(myPreds, price) %&gt;%
  ggplot(aes(x = price, y = myPreds)) +
  geom_point() +
  geom_smooth(method = &#39;lm&#39;) +
  ggtitle(&quot;My predictions vs Actual Price&quot;) +
  theme_tq()</code></pre>
<p><img src="/post/hackerrank-competitions/hackerrank-compeitions_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The model does <em>okay</em> without any feature engineering or parameter optimisation using a grid search method.</p>
</div>
<div id="problem-3-imputing-missing-values---cross-section" class="section level4">
<h4>Problem 3: Imputing missing values - cross section</h4>
<p>For simplicity I load in the <code>iris</code> dataset and I create some random missing values since the <code>iris</code> data doesn’t have any.</p>
<pre class="r"><code># Load in the data
library(missForest)
data(iris)
data &lt;- iris</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-16">Table 5: </span>Iris dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
Sepal.Length
</th>
<th style="text-align:right;">
Sepal.Width
</th>
<th style="text-align:right;">
Petal.Length
</th>
<th style="text-align:right;">
Petal.Width
</th>
<th style="text-align:left;">
Species
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
5.1
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
1.4
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.9
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
1.4
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.7
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
1.3
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.6
</td>
<td style="text-align:right;">
3.1
</td>
<td style="text-align:right;">
1.5
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
3.6
</td>
<td style="text-align:right;">
1.4
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
5.4
</td>
<td style="text-align:right;">
3.9
</td>
<td style="text-align:right;">
1.7
</td>
<td style="text-align:right;">
0.4
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
</tbody>
</table>
<p>I generate some random missing data, i.e. 20% of the data is missing at random (MaR) or Missing Completely at Random (MCaR). This is an important issue for economists since much of the data we collect contains missing values, due to surveys not being filled correctly, or simply data not being very well colelcted. The below model allows us to <em>impute</em> the missing values using machine learning, avoiding simple averaging or simply removing the values all together.</p>
<pre><code>## [1] &quot;Create some random missing data&quot;</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-17">Table 6: </span>Iris dataset with random missing values
</caption>
<thead>
<tr>
<th style="text-align:right;">
Sepal.Length
</th>
<th style="text-align:right;">
Sepal.Width
</th>
<th style="text-align:right;">
Petal.Length
</th>
<th style="text-align:right;">
Petal.Width
</th>
<th style="text-align:left;">
Species
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
5.1
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
1.4
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.9
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
1.4
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
1.3
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.6
</td>
<td style="text-align:right;">
3.1
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
3.6
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.2
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
5.4
</td>
<td style="text-align:right;">
3.9
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.4
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
</tbody>
</table>
<p>Okay now we can train a series of simple missing value imputation models on the data.</p>
</div>
<div id="model-1-randomforest-imputation" class="section level1">
<h1>Model 1: randomForest Imputation:</h1>
<p>I won’t discuss the models here but random forests uses a collection of decision trees and averages the results across all trees, which results it some powerful predictions.</p>
<pre><code>##   missForest iteration 1 in progress...done!
##   missForest iteration 2 in progress...done!
##   missForest iteration 3 in progress...done!
##   missForest iteration 4 in progress...done!
##   missForest iteration 5 in progress...done!
##   missForest iteration 6 in progress...done!
##   missForest iteration 7 in progress...done!</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-19">Table 7: </span>Iris dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
Sepal.Length
</th>
<th style="text-align:right;">
Sepal.Width
</th>
<th style="text-align:right;">
Petal.Length
</th>
<th style="text-align:right;">
Petal.Width
</th>
<th style="text-align:left;">
Species
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
5.100000
</td>
<td style="text-align:right;">
3.5
</td>
<td style="text-align:right;">
1.400000
</td>
<td style="text-align:right;">
0.2000000
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.900000
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
1.400000
</td>
<td style="text-align:right;">
0.1415167
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.722635
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
1.300000
</td>
<td style="text-align:right;">
0.2000000
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
4.600000
</td>
<td style="text-align:right;">
3.1
</td>
<td style="text-align:right;">
1.197250
</td>
<td style="text-align:right;">
0.2000000
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
5.000000
</td>
<td style="text-align:right;">
3.6
</td>
<td style="text-align:right;">
1.409930
</td>
<td style="text-align:right;">
0.2000000
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
<tr>
<td style="text-align:right;">
5.400000
</td>
<td style="text-align:right;">
3.9
</td>
<td style="text-align:right;">
1.419667
</td>
<td style="text-align:right;">
0.4000000
</td>
<td style="text-align:left;">
setosa
</td>
</tr>
</tbody>
</table>
<p>Lets combine all the data together, filter it down to the actual data, the missing data and the predicted data.</p>
<div id="for-the-sepal.length-data" class="section level3">
<h3>For the Sepal.Length data</h3>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 12px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-20">Table 8: </span>Compare Sepal Observations
</caption>
<thead>
<tr>
<th style="text-align:right;">
Predicted_Sepal
</th>
<th style="text-align:right;">
Actual_Sepal
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
6.3
</td>
<td style="text-align:right;">
6.9
</td>
</tr>
<tr>
<td style="text-align:right;">
5.1
</td>
<td style="text-align:right;">
5.0
</td>
</tr>
<tr>
<td style="text-align:right;">
7.0
</td>
<td style="text-align:right;">
6.3
</td>
</tr>
<tr>
<td style="text-align:right;">
5.7
</td>
<td style="text-align:right;">
5.6
</td>
</tr>
<tr>
<td style="text-align:right;">
5.1
</td>
<td style="text-align:right;">
5.1
</td>
</tr>
<tr>
<td style="text-align:right;">
6.2
</td>
<td style="text-align:right;">
6.5
</td>
</tr>
<tr>
<td style="text-align:right;">
4.7
</td>
<td style="text-align:right;">
4.8
</td>
</tr>
<tr>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
5.8
</td>
</tr>
<tr>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.9
</td>
</tr>
<tr>
<td style="text-align:right;">
5.6
</td>
<td style="text-align:right;">
5.8
</td>
</tr>
</tbody>
</table>
<p>Which isn’t bad! given that we only had 436 observations to train on and only 110 observations to test on. Using <code>randomForest</code> models to impute the data is better than averaging the data on some datasets, of course we have errors the actual observations are somewhat close to the predicted data. I only analyse the <code>Sepal.Length</code> data but substitute the values to find the missing values for the <code>Sepal.Width</code>, <code>Petal.Length</code>, <code>Petal.Width</code> and <code>Species</code> values since <code>missorest</code> imputes categorical variables as well.</p>
</div>
</div>
